name: s1-frame-generation
channels:
  - conda-forge
dependencies:
  - python=>3.11
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - ipympl
  - setuptools
  - setuptools_scm
  - wheel
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # jupyter
  - jupyter
  - ipykernel
  # gis
  - rasterio
  - geopandas
  - shapely>=2.0.0
  - tqdm
  - requests
  - asf_search
  - hyp3_sdk
  - dask-geopandas
  - dem_stitcher
